apiVersion: v1
kind: Service
metadata:
  name: test-deny-externalip
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dummy
  externalIPs:
    - 203.0.113.123
