apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged-priv
  namespace: ns-privileged
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        privileged: true
