apiVersion: v1
kind: Pod
metadata:
  name: pod-baseline-violate
  namespace: ns-baseline
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        privileged: true
