apiVersion: v1
kind: Pod
metadata:
  name: big-request-pod
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        requests:
          cpu: "600m"
          memory: "100Mi"
        limits:
          cpu: "800m"
          memory: "150Mi"
