apiVersion: v1
kind: Pod
metadata:
  name: small-pod
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        requests:
          cpu: "100m"
          memory: "50Mi"
        limits:
          cpu: "200m"
          memory: "100Mi"
