apiVersion: v1
kind: Pod
metadata:
  name: no-token-pod
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
