apiVersion: v1
kind: Pod
metadata:
  name: token-request-pod
  namespace: default
spec:
  serviceAccountName: default
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "Waiting for token to be available..."
          while [ ! -f /var/run/secrets/tokens/my-token ]; do
            echo "Token not ready yet, waiting..."
            sleep 1
          done
          echo "TOKEN:" && cat /var/run/secrets/tokens/my-token && sleep 3600
      volumeMounts:
        - name: sa-token # ← ここは volumes.name と同じに
          mountPath: /var/run/secrets/tokens
          readOnly: true
  volumes:
    - name: sa-token # ← ここも同じ名前
      projected:
        sources:
          - serviceAccountToken:
              path: my-token
              expirationSeconds: 600 # ← 最低 600 秒（10 分）に
