apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-limited
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-noperms
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-noperms
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sa-limited
    namespace: default
roleRef:
  kind: Role
  name: role-noperms
  apiGroup: rbac.authorization.k8s.io
