apiVersion: v1
kind: LimitRange
metadata:
  name: pod-default-limits
  namespace: lr-test
spec:
  limits:
    # ── Pod 全体の min/max 制限
    - type: Pod
      min:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "500m"
        memory: "512Mi"

    # ── 各コンテナの default/defaultRequest, min/max 制限
    - type: Container
      min:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "150m"
        memory: "192Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
