apiVersion: v1
kind: Pod
metadata:
  name: nginx-above-max
  namespace: lr-test
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        limits:
          cpu: "600m" # max 500m を超過
