apiVersion: v1
kind: Pod
metadata:
  name: nginx-below-min
  namespace: lr-test
spec:
  containers:
    - name: nginx
      image: nginx:stable
      resources:
        requests:
          cpu: "50m"
