apiVersion: v1
kind: Pod
metadata:
  name: test-alwayspull-no-spec
  namespace: test
spec:
  containers:
    - name: busybox
      image: busybox:1.35
      # imagePullPolicy: 未指定
      command: ["sleep", "3600"]
